name    'herculesteam-augeasproviders_postgresql'
version '1.0.0'
source 'git://github.com/hercules-team/augeasproviders_postgresql'
author 'Dominic Cleal, Raphael Pinson'
license 'Apache 2.0'
summary 'Augeas-based postgresql types and providers for Puppet'
description 'This module provides types/providers for postgresql using the Augeas configuration API library.'
project_page 'http://augeasproviders.com'
